"""Move database (template)."""

MOVE_DATABASE = {
    "air_slash": {
        "name": "Air Slash",
        "type": 'Flying',
        "category": 'Special',
        "power": 75,
        "accuracy": 95,
        "pp": 15,
        "priority": 0,
        "target": 'selected',
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": 'flinch',
        "effect_chance": 30,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": 'High critical-pressure special attack',
    },
    "aura_sphere": {
        "name": "Aura Sphere",
        "type": 'Fighting',
        "category": 'Special',
        "power": 80,
        "accuracy": 0,
        "pp": 20,
        "priority": 0,
        "target": 'selected',
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": 'Never misses',
    },
    "aurora_veil": {
        "name": "Aurora Veil",
        "type": 'Ice',
        "category": 'Status',
        "power": 0,
        "accuracy": 0,
        "pp": 20,
        "priority": 0,
        "target": 'ally_side',
        "makes_contact": False,
        "protectable": False,
        "spread_move": False,
        "secondary_effect": 'aurora_veil',
        "effect_chance": 100,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": 'Halves damage for 5 turns in Snow.',
    },
    "blizzard": {
        "name": "Blizzard",
        "type": 'Ice',
        "category": 'Special',
        "power": 110,
        "accuracy": 70,
        "pp": 5,
        "priority": 0,
        "target": 'all_adjacent_foes',
        "makes_contact": False,
        "protectable": True,
        "spread_move": True,
        "secondary_effect": 'freeze',
        "effect_chance": 10,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": '100% accurate in snow',
    },
    "close_combat": {
        "name": "Close Combat",
        "type": 'Fighting',
        "category": 'Physical',
        "power": 120,
        "accuracy": 100,
        "pp": 5,
        "priority": 0,
        "target": 'selected',
        "makes_contact": True,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {'self': {'def': -1, 'spd': -1}},
        "status_inflicted": None,
        "notes": "Lowers user's Defense and Sp. Def by 1 stage.",
    },
    "dire_claw": {
        "name": "Dire Claw",
        "type": 'Poison',
        "category": 'Physical',
        "power": 80,
        "accuracy": 100,
        "pp": 15,
        "priority": 0,
        "target": 'selected',
        "makes_contact": True,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": 'random_status',
        "effect_chance": 50,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": '50% chance to poison, paralyze, or sleep.',
    },
    "eruption": {
        "name": "Eruption",
        "type": 'Fire',
        "category": 'Special',
        "power": 150,
        "accuracy": 100,
        "pp": 5,
        "priority": 0,
        "target": 'all_adjacent_foes',
        "makes_contact": False,
        "protectable": True,
        "spread_move": True,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "Power decreases as user's HP decreases.",
    },
    "fake_out": {
        "name": "Fake Out",
        "type": 'Normal',
        "category": 'Physical',
        "power": 40,
        "accuracy": 100,
        "pp": 10,
        "priority": 3,
        "target": 'selected',
        "makes_contact": True,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": 'flinch',
        "effect_chance": 100,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": 'Only works on first turn after entering battle.',
    },
    "fire_punch": {
        "name": "Fire Punch",
        "type": 'Fire',
        "category": 'Physical',
        "power": 75,
        "accuracy": 100,
        "pp": 15,
        "priority": 0,
        "target": 'selected',
        "makes_contact": True,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": 'burn',
        "effect_chance": 10,
        "stat_changes": {},
        "status_inflicted": 'burn',
        "notes": '',
    },
    "flare_blitz": {
        "name": "Flare Blitz",
        "type": 'Fire',
        "category": 'Physical',
        "power": 120,
        "accuracy": 100,
        "pp": 15,
        "priority": 0,
        "target": 'selected',
        "makes_contact": True,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": 'burn',
        "effect_chance": 10,
        "stat_changes": {},
        "status_inflicted": 'burn',
        "notes": '1/3 recoil.',
    },
    "flash_cannon": {
        "name": "Flash Cannon",
        "type": 'Steel',
        "category": 'Special',
        "power": 80,
        "accuracy": 100,
        "pp": 10,
        "priority": 0,
        "target": 'selected',
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": 'spdef_down',
        "effect_chance": 10,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": '',
    },
    "haze": {
        "name": "Haze",
        "type": 'Ice',
        "category": 'Status',
        "power": 0,
        "accuracy": 0,
        "pp": 30,
        "priority": 0,
        "target": 'all',
        "makes_contact": False,
        "protectable": False,
        "spread_move": True,
        "secondary_effect": 'clear_stat_changes',
        "effect_chance": 100,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": 'Resets all stat changes.',
    },
    "heat_wave": {
        "name": "Heat Wave",
        "type": 'Fire',
        "category": 'Special',
        "power": 95,
        "accuracy": 90,
        "pp": 10,
        "priority": 0,
        "target": 'all_adjacent_foes',
        "makes_contact": False,
        "protectable": True,
        "spread_move": True,
        "secondary_effect": 'burn',
        "effect_chance": 10,
        "stat_changes": {},
        "status_inflicted": 'burn',
        "notes": '',
    },
    "hydro_pump": {
        "name": "Hydro Pump",
        "type": 'Water',
        "category": 'Special',
        "power": 110,
        "accuracy": 80,
        "pp": 5,
        "priority": 0,
        "target": 'selected',
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": '',
    },
    "ice_beam": {
        "name": "Ice Beam",
        "type": 'Ice',
        "category": 'Special',
        "power": 90,
        "accuracy": 100,
        "pp": 10,
        "priority": 0,
        "target": 'selected',
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": 'freeze',
        "effect_chance": 10,
        "stat_changes": {},
        "status_inflicted": 'freeze',
        "notes": '',
    },
    "icy_wind": {
        "name": "Icy Wind",
        "type": 'Ice',
        "category": 'Special',
        "power": 55,
        "accuracy": 95,
        "pp": 15,
        "priority": 0,
        "target": 'all_adjacent_foes',
        "makes_contact": False,
        "protectable": True,
        "spread_move": True,
        "secondary_effect": 'speed_down',
        "effect_chance": 100,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": 'Lowers Speed by 1 stage.',
    },
    "ingrain": {
        "name": "Ingrain",
        "type": 'Grass',
        "category": 'Status',
        "power": 0,
        "accuracy": 0,
        "pp": 20,
        "priority": 0,
        "target": 'self',
        "makes_contact": False,
        "protectable": False,
        "spread_move": False,
        "secondary_effect": 'ingrain',
        "effect_chance": 100,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": 'Restores 1/16 max HP each turn; prevents switching.',
    },
    "knock_off": {
        "name": "Knock Off",
        "type": 'Dark',
        "category": 'Physical',
        "power": 65,
        "accuracy": 100,
        "pp": 20,
        "priority": 0,
        "target": 'selected',
        "makes_contact": True,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": 'remove_item',
        "effect_chance": 100,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": 'Power increases when target holds removable item.',
    },
    "leech_seed": {
        "name": "Leech Seed",
        "type": 'Grass',
        "category": 'Status',
        "power": 0,
        "accuracy": 90,
        "pp": 10,
        "priority": 0,
        "target": 'selected',
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": 'leech_seed',
        "effect_chance": 100,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": 'Drains 1/8 max HP each turn.',
    },
    "mean_look": {
        "name": "Mean Look",
        "type": 'Normal',
        "category": 'Status',
        "power": 0,
        "accuracy": 100,
        "pp": 5,
        "priority": 0,
        "target": 'selected',
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": 'trap',
        "effect_chance": 100,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": 'Prevents target from switching or fleeing.',
    },
    "moonblast": {
        "name": "Moonblast",
        "type": 'Fairy',
        "category": 'Special',
        "power": 95,
        "accuracy": 100,
        "pp": 15,
        "priority": 0,
        "target": 'selected',
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": 'spatk_down',
        "effect_chance": 30,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "May lower target's Sp. Atk by 1 stage.",
    },
    "nasty_plot": {
        "name": "Nasty Plot",
        "type": 'Dark',
        "category": 'Status',
        "power": 0,
        "accuracy": 0,
        "pp": 20,
        "priority": 0,
        "target": 'self',
        "makes_contact": False,
        "protectable": False,
        "spread_move": False,
        "secondary_effect": 'raise_spatk',
        "effect_chance": 100,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "Raises user's Sp. Atk by 2 stages.",
    },
    "overheat": {
        "name": "Overheat",
        "type": 'Fire',
        "category": 'Special',
        "power": 130,
        "accuracy": 90,
        "pp": 5,
        "priority": 0,
        "target": 'selected',
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": 'self_spatk_down',
        "effect_chance": 100,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "Lowers user's Sp. Atk by 2 stages.",
    },
    "parting_shot": {
        "name": "Parting Shot",
        "type": 'Dark',
        "category": 'Status',
        "power": 0,
        "accuracy": 100,
        "pp": 20,
        "priority": 0,
        "target": 'selected',
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": 'pivot',
        "effect_chance": 100,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "Lowers target's Attack and Sp. Atk by 1 stage, then switches user.",
    },
    "perish_song": {
        "name": "Perish Song",
        "type": 'Normal',
        "category": 'Status',
        "power": 0,
        "accuracy": 0,
        "pp": 5,
        "priority": 0,
        "target": 'all',
        "makes_contact": False,
        "protectable": False,
        "spread_move": True,
        "secondary_effect": 'perish_song',
        "effect_chance": 100,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": 'All active Pokémon faint after 3 turns unless switched.',
    },
    "precipice_blades": {
        "name": "Precipice Blades",
        "type": 'Ground',
        "category": 'Physical',
        "power": 120,
        "accuracy": 85,
        "pp": 10,
        "priority": 0,
        "target": 'all_adjacent_foes',
        "makes_contact": False,
        "protectable": True,
        "spread_move": True,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": '',
    },
    "protect": {
        "name": "Protect",
        "type": 'Normal',
        "category": 'Status',
        "power": 0,
        "accuracy": 0,
        "pp": 10,
        "priority": 4,
        "target": 'self',
        "makes_contact": False,
        "protectable": False,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": 'Blocks most moves',
    },
    "rock_slide": {
        "name": "Rock Slide",
        "type": 'Rock',
        "category": 'Physical',
        "power": 75,
        "accuracy": 90,
        "pp": 10,
        "priority": 0,
        "target": 'all_adjacent_foes',
        "makes_contact": False,
        "protectable": True,
        "spread_move": True,
        "secondary_effect": 'flinch',
        "effect_chance": 30,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": '',
    },
    "shadow_ball": {
        "name": "Shadow Ball",
        "type": 'Ghost',
        "category": 'Special',
        "power": 80,
        "accuracy": 100,
        "pp": 15,
        "priority": 0,
        "target": 'selected',
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": 'spdef_down',
        "effect_chance": 20,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "May lower target's Sp. Def by 1 stage.",
    },
    "sleep_powder": {
        "name": "Sleep Powder",
        "type": 'Grass',
        "category": 'Status',
        "power": 0,
        "accuracy": 75,
        "pp": 15,
        "priority": 0,
        "target": 'selected',
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": 'sleep',
        "effect_chance": 100,
        "stat_changes": {},
        "status_inflicted": 'sleep',
        "notes": 'Puts the target to sleep.',
    },
    "sludge_bomb": {
        "name": "Sludge Bomb",
        "type": 'Poison',
        "category": 'Special',
        "power": 90,
        "accuracy": 100,
        "pp": 10,
        "priority": 0,
        "target": 'selected',
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": 'poison',
        "effect_chance": 30,
        "stat_changes": {},
        "status_inflicted": 'poison',
        "notes": 'May poison the target.',
    },
    "sunny_day": {
        "name": "Sunny Day",
        "type": 'Fire',
        "category": 'Status',
        "power": 0,
        "accuracy": 0,
        "pp": 5,
        "priority": 0,
        "target": 'field',
        "makes_contact": False,
        "protectable": False,
        "spread_move": False,
        "secondary_effect": 'sun',
        "effect_chance": 100,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": 'Creates harsh sunlight for 5 turns.',
    },
    "swords_dance": {
        "name": "Swords Dance",
        "type": 'Normal',
        "category": 'Status',
        "power": 0,
        "accuracy": 0,
        "pp": 20,
        "priority": 0,
        "target": 'self',
        "makes_contact": False,
        "protectable": False,
        "spread_move": False,
        "secondary_effect": 'raise_attack',
        "effect_chance": 100,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "Raises user's Attack by 2 stages.",
    },
    "tailwind": {
        "name": "Tailwind",
        "type": 'Flying',
        "category": 'Status',
        "power": 0,
        "accuracy": 0,
        "pp": 15,
        "priority": 0,
        "target": 'ally_side',
        "makes_contact": False,
        "protectable": False,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": 'Doubles Speed for 4 turns',
    },
    "toxic": {
        "name": "Toxic",
        "type": "",
        "category": "",
        "power": 0,
        "accuracy": 100,
        "pp": 0,
        "priority": 0,
        "target": "selected",
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "",
    },
    "vacuum_wave": {
        "name": "Vacuum Wave",
        "type": "",
        "category": "",
        "power": 0,
        "accuracy": 100,
        "pp": 0,
        "priority": 0,
        "target": "selected",
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "",
    },
    "wood_hammer": {
        "name": "Wood Hammer",
        "type": "",
        "category": "",
        "power": 0,
        "accuracy": 100,
        "pp": 0,
        "priority": 0,
        "target": "selected",
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "",
    },
    "yawn": {
        "name": "Yawn",
        "type": "",
        "category": "",
        "power": 0,
        "accuracy": 100,
        "pp": 0,
        "priority": 0,
        "target": "selected",
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "",
    },
}