"""Move database (template)."""

MOVE_DATABASE = {
    "air_slash": {
        "name": "Air Slash",
        "type": 'Flying',
        "category": 'Special',
        "power": 75,
        "accuracy": 95,
        "pp": 15,
        "priority": 0,
        "target": 'selected',
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": 'flinch',
        "effect_chance": 30,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": 'High critical-pressure special attack',
    },
    "aura_sphere": {
        "name": "Aura Sphere",
        "type": 'Fighting',
        "category": 'Special',
        "power": 80,
        "accuracy": 0,
        "pp": 20,
        "priority": 0,
        "target": 'selected',
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": 'Never misses',
    },
    "aurora_veil": {
        "name": "Aurora Veil",
        "type": "",
        "category": "",
        "power": 0,
        "accuracy": 100,
        "pp": 0,
        "priority": 0,
        "target": "selected",
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "",
    },
    "blizzard": {
        "name": "Blizzard",
        "type": 'Ice',
        "category": 'Special',
        "power": 110,
        "accuracy": 70,
        "pp": 5,
        "priority": 0,
        "target": 'all_adjacent_foes',
        "makes_contact": False,
        "protectable": True,
        "spread_move": True,
        "secondary_effect": 'freeze',
        "effect_chance": 10,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": '100% accurate in snow',
    },
    "close_combat": {
        "name": "Close Combat",
        "type": 'Fighting',
        "category": 'Physical',
        "power": 120,
        "accuracy": 100,
        "pp": 5,
        "priority": 0,
        "target": 'selected',
        "makes_contact": True,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {'self': {'def': -1, 'spd': -1}},
        "status_inflicted": None,
        "notes": "Lowers user's Defense and Sp. Def by 1 stage.",
    },
    "dire_claw": {
        "name": "Dire Claw",
        "type": "",
        "category": "",
        "power": 0,
        "accuracy": 100,
        "pp": 0,
        "priority": 0,
        "target": "selected",
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "",
    },
    "eruption": {
        "name": "Eruption",
        "type": "",
        "category": "",
        "power": 0,
        "accuracy": 100,
        "pp": 0,
        "priority": 0,
        "target": "selected",
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "",
    },
    "fake_out": {
        "name": "Fake Out",
        "type": "",
        "category": "",
        "power": 0,
        "accuracy": 100,
        "pp": 0,
        "priority": 0,
        "target": "selected",
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "",
    },
    "fire_punch": {
        "name": "Fire Punch",
        "type": 'Fire',
        "category": 'Physical',
        "power": 75,
        "accuracy": 100,
        "pp": 15,
        "priority": 0,
        "target": 'selected',
        "makes_contact": True,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": 'burn',
        "effect_chance": 10,
        "stat_changes": {},
        "status_inflicted": 'burn',
        "notes": '',
    },
    "flare_blitz": {
        "name": "Flare Blitz",
        "type": 'Fire',
        "category": 'Physical',
        "power": 120,
        "accuracy": 100,
        "pp": 15,
        "priority": 0,
        "target": 'selected',
        "makes_contact": True,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": 'burn',
        "effect_chance": 10,
        "stat_changes": {},
        "status_inflicted": 'burn',
        "notes": '1/3 recoil.',
    },
    "flash_cannon": {
        "name": "Flash Cannon",
        "type": 'Steel',
        "category": 'Special',
        "power": 80,
        "accuracy": 100,
        "pp": 10,
        "priority": 0,
        "target": 'selected',
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": 'spdef_down',
        "effect_chance": 10,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": '',
    },
    "haze": {
        "name": "Haze",
        "type": "",
        "category": "",
        "power": 0,
        "accuracy": 100,
        "pp": 0,
        "priority": 0,
        "target": "selected",
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "",
    },
    "heat_wave": {
        "name": "Heat Wave",
        "type": 'Fire',
        "category": 'Special',
        "power": 95,
        "accuracy": 90,
        "pp": 10,
        "priority": 0,
        "target": 'all_adjacent_foes',
        "makes_contact": False,
        "protectable": True,
        "spread_move": True,
        "secondary_effect": 'burn',
        "effect_chance": 10,
        "stat_changes": {},
        "status_inflicted": 'burn',
        "notes": '',
    },
    "hydro_pump": {
        "name": "Hydro Pump",
        "type": 'Water',
        "category": 'Special',
        "power": 110,
        "accuracy": 80,
        "pp": 5,
        "priority": 0,
        "target": 'selected',
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": '',
    },
    "ice_beam": {
        "name": "Ice Beam",
        "type": 'Ice',
        "category": 'Special',
        "power": 90,
        "accuracy": 100,
        "pp": 10,
        "priority": 0,
        "target": 'selected',
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": 'freeze',
        "effect_chance": 10,
        "stat_changes": {},
        "status_inflicted": 'freeze',
        "notes": '',
    },
    "icy_wind": {
        "name": "Icy Wind",
        "type": 'Ice',
        "category": 'Special',
        "power": 55,
        "accuracy": 95,
        "pp": 15,
        "priority": 0,
        "target": 'all_adjacent_foes',
        "makes_contact": False,
        "protectable": True,
        "spread_move": True,
        "secondary_effect": 'speed_down',
        "effect_chance": 100,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": 'Lowers Speed by 1 stage.',
    },
    "ingrain": {
        "name": "Ingrain",
        "type": "",
        "category": "",
        "power": 0,
        "accuracy": 100,
        "pp": 0,
        "priority": 0,
        "target": "selected",
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "",
    },
    "knock_off": {
        "name": "Knock Off",
        "type": 'Dark',
        "category": 'Physical',
        "power": 65,
        "accuracy": 100,
        "pp": 20,
        "priority": 0,
        "target": 'selected',
        "makes_contact": True,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": 'remove_item',
        "effect_chance": 100,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": 'Power increases when target holds removable item.',
    },
    "leech_seed": {
        "name": "Leech Seed",
        "type": 'Grass',
        "category": 'Status',
        "power": 0,
        "accuracy": 90,
        "pp": 10,
        "priority": 0,
        "target": 'selected',
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": 'leech_seed',
        "effect_chance": 100,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": 'Drains 1/8 max HP each turn.',
    },
    "mean_look": {
        "name": "Mean Look",
        "type": "",
        "category": "",
        "power": 0,
        "accuracy": 100,
        "pp": 0,
        "priority": 0,
        "target": "selected",
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "",
    },
    "moonblast": {
        "name": "Moonblast",
        "type": "",
        "category": "",
        "power": 0,
        "accuracy": 100,
        "pp": 0,
        "priority": 0,
        "target": "selected",
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "",
    },
    "nasty_plot": {
        "name": "Nasty Plot",
        "type": "",
        "category": "",
        "power": 0,
        "accuracy": 100,
        "pp": 0,
        "priority": 0,
        "target": "selected",
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "",
    },
    "overheat": {
        "name": "Overheat",
        "type": "",
        "category": "",
        "power": 0,
        "accuracy": 100,
        "pp": 0,
        "priority": 0,
        "target": "selected",
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "",
    },
    "parting_shot": {
        "name": "Parting Shot",
        "type": "",
        "category": "",
        "power": 0,
        "accuracy": 100,
        "pp": 0,
        "priority": 0,
        "target": "selected",
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "",
    },
    "perish_song": {
        "name": "Perish Song",
        "type": "",
        "category": "",
        "power": 0,
        "accuracy": 100,
        "pp": 0,
        "priority": 0,
        "target": "selected",
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "",
    },
    "precipice_blades": {
        "name": "Precipice Blades",
        "type": "",
        "category": "",
        "power": 0,
        "accuracy": 100,
        "pp": 0,
        "priority": 0,
        "target": "selected",
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "",
    },
    "protect": {
        "name": "Protect",
        "type": 'Normal',
        "category": 'Status',
        "power": 0,
        "accuracy": 0,
        "pp": 10,
        "priority": 4,
        "target": 'self',
        "makes_contact": False,
        "protectable": False,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": 'Blocks most moves',
    },
    "rock_slide": {
        "name": "Rock Slide",
        "type": "",
        "category": "",
        "power": 0,
        "accuracy": 100,
        "pp": 0,
        "priority": 0,
        "target": "selected",
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "",
    },
    "shadow_ball": {
        "name": "Shadow Ball",
        "type": "",
        "category": "",
        "power": 0,
        "accuracy": 100,
        "pp": 0,
        "priority": 0,
        "target": "selected",
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "",
    },
    "sleep_powder": {
        "name": "Sleep Powder",
        "type": "",
        "category": "",
        "power": 0,
        "accuracy": 100,
        "pp": 0,
        "priority": 0,
        "target": "selected",
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "",
    },
    "sludge_bomb": {
        "name": "Sludge Bomb",
        "type": "",
        "category": "",
        "power": 0,
        "accuracy": 100,
        "pp": 0,
        "priority": 0,
        "target": "selected",
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "",
    },
    "sunny_day": {
        "name": "Sunny Day",
        "type": "",
        "category": "",
        "power": 0,
        "accuracy": 100,
        "pp": 0,
        "priority": 0,
        "target": "selected",
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "",
    },
    "swords_dance": {
        "name": "Swords Dance",
        "type": "",
        "category": "",
        "power": 0,
        "accuracy": 100,
        "pp": 0,
        "priority": 0,
        "target": "selected",
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "",
    },
    "tailwind": {
        "name": "Tailwind",
        "type": 'Flying',
        "category": 'Status',
        "power": 0,
        "accuracy": 0,
        "pp": 15,
        "priority": 0,
        "target": 'ally_side',
        "makes_contact": False,
        "protectable": False,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": 'Doubles Speed for 4 turns',
    },
    "toxic": {
        "name": "Toxic",
        "type": "",
        "category": "",
        "power": 0,
        "accuracy": 100,
        "pp": 0,
        "priority": 0,
        "target": "selected",
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "",
    },
    "vacuum_wave": {
        "name": "Vacuum Wave",
        "type": "",
        "category": "",
        "power": 0,
        "accuracy": 100,
        "pp": 0,
        "priority": 0,
        "target": "selected",
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "",
    },
    "wood_hammer": {
        "name": "Wood Hammer",
        "type": "",
        "category": "",
        "power": 0,
        "accuracy": 100,
        "pp": 0,
        "priority": 0,
        "target": "selected",
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "",
    },
    "yawn": {
        "name": "Yawn",
        "type": "",
        "category": "",
        "power": 0,
        "accuracy": 100,
        "pp": 0,
        "priority": 0,
        "target": "selected",
        "makes_contact": False,
        "protectable": True,
        "spread_move": False,
        "secondary_effect": None,
        "effect_chance": 0,
        "stat_changes": {},
        "status_inflicted": None,
        "notes": "",
    },
}