"""Species database for the Pokémon Battle Engine.

Only populated species/forms used by the project are included here.
Base stats are canonical species data; individual IV/EV/nature calculations
are handled by the Pokémon/stat system.
"""

SPECIES = {
    'Gengar': {'base_stats': {'hp': 60, 'attack': 65, 'defense': 60, 'special_attack': 130, 'special_defense': 75, 'speed': 110}, 'types': ['Ghost', 'Poison']},
    'Incineroar': {'base_stats': {'hp': 95, 'attack': 115, 'defense': 90, 'special_attack': 80, 'special_defense': 90, 'speed': 60}, 'types': ['Fire', 'Dark']},
    'Sneasler': {'base_stats': {'hp': 80, 'attack': 130, 'defense': 60, 'special_attack': 40, 'special_defense': 80, 'speed': 120}, 'types': ['Fighting', 'Poison']},
    'Cresselia': {'base_stats': {'hp': 120, 'attack': 70, 'defense': 120, 'special_attack': 75, 'special_defense': 130, 'speed': 85}, 'types': ['Psychic']},
    'Kilowattrel': {'base_stats': {'hp': 70, 'attack': 70, 'defense': 60, 'special_attack': 105, 'special_defense': 60, 'speed': 125}, 'types': ['Electric', 'Flying']},
    'Sinistcha': {'base_stats': {'hp': 71, 'attack': 60, 'defense': 106, 'special_attack': 121, 'special_defense': 80, 'speed': 70}, 'types': ['Grass', 'Ghost']},
    'Calyrex-Ice': {'base_stats': {'hp': 100, 'attack': 165, 'defense': 150, 'special_attack': 85, 'special_defense': 130, 'speed': 50}, 'types': ['Psychic', 'Ice']},
    'Indeedee-F': {'base_stats': {'hp': 70, 'attack': 55, 'defense': 65, 'special_attack': 95, 'special_defense': 105, 'speed': 85}, 'types': ['Psychic', 'Normal']},
    'Lunala': {'base_stats': {'hp': 137, 'attack': 113, 'defense': 89, 'special_attack': 137, 'special_defense': 107, 'speed': 97}, 'types': ['Psychic', 'Ghost']},
    'Ursaluna': {'base_stats': {'hp': 130, 'attack': 140, 'defense': 105, 'special_attack': 45, 'special_defense': 80, 'speed': 50}, 'types': ['Ground', 'Normal']},
    'Torkoal': {'base_stats': {'hp': 70, 'attack': 85, 'defense': 140, 'special_attack': 85, 'special_defense': 70, 'speed': 20}, 'types': ['Fire']},
    'Houndoom': {'base_stats': {'hp': 75, 'attack': 90, 'defense': 50, 'special_attack': 110, 'special_defense': 80, 'speed': 95}, 'types': ['Dark', 'Fire']},
    'Mega Houndoom': {'base_stats': {'hp': 75, 'attack': 90, 'defense': 90, 'special_attack': 140, 'special_defense': 90, 'speed': 115}, 'types': ['Dark', 'Fire'], 'ability': 'Solar Power'},
    'Talonflame': {'base_stats': {'hp': 78, 'attack': 81, 'defense': 71, 'special_attack': 74, 'special_defense': 69, 'speed': 126}, 'types': ['Fire', 'Flying']},
    'Iron Hands': {'base_stats': {'hp': 154, 'attack': 140, 'defense': 108, 'special_attack': 50, 'special_defense': 68, 'speed': 50}, 'types': ['Fighting', 'Electric']},
    'Alakazam': {'base_stats': {'hp': 55, 'attack': 50, 'defense': 45, 'special_attack': 135, 'special_defense': 95, 'speed': 120}, 'types': ['Psychic']},
    'Clefable': {'base_stats': {'hp': 95, 'attack': 70, 'defense': 73, 'special_attack': 95, 'special_defense': 90, 'speed': 60}, 'types': ['Fairy']},
    'Scizor': {'base_stats': {'hp': 70, 'attack': 130, 'defense': 100, 'special_attack': 55, 'special_defense': 80, 'speed': 65}, 'types': ['Bug', 'Steel']},
    'Tyranitar': {'base_stats': {'hp': 100, 'attack': 134, 'defense': 110, 'special_attack': 95, 'special_defense': 100, 'speed': 61}, 'types': ['Rock', 'Dark']},
    'Mega Tyranitar': {'base_stats': {'hp': 100, 'attack': 164, 'defense': 150, 'special_attack': 95, 'special_defense': 120, 'speed': 71}, 'types': ['Rock', 'Dark']},
    'Excadrill': {'base_stats': {'hp': 110, 'attack': 135, 'defense': 60, 'special_attack': 50, 'special_defense': 65, 'speed': 88}, 'types': ['Ground', 'Steel']},
    'Milotic': {'base_stats': {'hp': 95, 'attack': 60, 'defense': 79, 'special_attack': 100, 'special_defense': 125, 'speed': 81}, 'types': ['Water']},
    'Volcarona': {'base_stats': {'hp': 85, 'attack': 60, 'defense': 65, 'special_attack': 135, 'special_defense': 105, 'speed': 100}, 'types': ['Bug', 'Fire']},
    'Aegislash': {'base_stats': {'hp': 60, 'attack': 50, 'defense': 140, 'special_attack': 50, 'special_defense': 140, 'speed': 60}, 'types': ['Steel', 'Ghost']},
    'Amoonguss': {'base_stats': {'hp': 114, 'attack': 85, 'defense': 70, 'special_attack': 85, 'special_defense': 80, 'speed': 30}, 'types': ['Grass', 'Poison']},
    'Gholdengo': {'base_stats': {'hp': 87, 'attack': 60, 'defense': 95, 'special_attack': 133, 'special_defense': 91, 'speed': 84}, 'types': ['Steel', 'Ghost']},
    'Dragonite': {'base_stats': {'hp': 91, 'attack': 134, 'defense': 95, 'special_attack': 100, 'special_defense': 100, 'speed': 80}, 'types': ['Dragon', 'Flying']},
    'Archaludon': {'base_stats': {'hp': 90, 'attack': 105, 'defense': 130, 'special_attack': 125, 'special_defense': 65, 'speed': 85}, 'types': ['Steel', 'Dragon']},
    'Rotom-Wash': {'base_stats': {'hp': 50, 'attack': 65, 'defense': 107, 'special_attack': 105, 'special_defense': 107, 'speed': 86}, 'types': ['Electric', 'Water']},
    'Groudon': {'base_stats': {'hp': 100, 'attack': 150, 'defense': 140, 'special_attack': 100, 'special_defense': 90, 'speed': 90}, 'types': ['Ground']},
    'Primal Groudon': {'base_stats': {'hp': 100, 'attack': 180, 'defense': 160, 'special_attack': 150, 'special_defense': 90, 'speed': 90}, 'types': ['Ground', 'Fire']},
    'Charizard': {'base_stats': {'hp': 78, 'attack': 84, 'defense': 78, 'special_attack': 109, 'special_defense': 85, 'speed': 100}, 'types': ['Fire', 'Flying']},
    'Venusaur': {'base_stats': {'hp': 80, 'attack': 82, 'defense': 83, 'special_attack': 100, 'special_defense': 100, 'speed': 80}, 'types': ['Grass', 'Poison']},
    'Flutter Mane': {'base_stats': {'hp': 55, 'attack': 55, 'defense': 55, 'special_attack': 135, 'special_defense': 135, 'speed': 135}, 'types': ['Ghost', 'Fairy']},
    'Pelipper': {'base_stats': {'hp': 60, 'attack': 50, 'defense': 100, 'special_attack': 95, 'special_defense': 70, 'speed': 65}, 'types': ['Water', 'Flying']},
    'Barraskewda': {'base_stats': {'hp': 61, 'attack': 123, 'defense': 60, 'special_attack': 60, 'special_defense': 50, 'speed': 136}, 'types': ['Water']},
    'Swampert': {'base_stats': {'hp': 100, 'attack': 110, 'defense': 90, 'special_attack': 85, 'special_defense': 90, 'speed': 60}, 'types': ['Water', 'Ground']},
    'Mega Swampert': {'base_stats': {'hp': 100, 'attack': 150, 'defense': 110, 'special_attack': 95, 'special_defense': 110, 'speed': 70}, 'types': ['Water', 'Ground'], 'ability': 'Swift Swim'},
    'Politoed': {'base_stats': {'hp': 90, 'attack': 75, 'defense': 75, 'special_attack': 90, 'special_defense': 100, 'speed': 70}, 'types': ['Water']},
    'Kingdra': {'base_stats': {'hp': 75, 'attack': 95, 'defense': 95, 'special_attack': 95, 'special_defense': 95, 'speed': 85}, 'types': ['Water', 'Dragon']},
    'Abomasnow': {'base_stats': {'hp': 90, 'attack': 92, 'defense': 75, 'special_attack': 92, 'special_defense': 85, 'speed': 60}, 'types': ['Grass', 'Ice']},
    'Lucario': {'base_stats': {'hp': 70, 'attack': 110, 'defense': 70, 'special_attack': 115, 'special_defense': 70, 'speed': 90}, 'types': ['Fighting', 'Steel']},
    'Mega Lucario': {'base_stats': {'hp': 70, 'attack': 145, 'defense': 88, 'special_attack': 140, 'special_defense': 70, 'speed': 112}, 'types': ['Fighting', 'Steel'], 'ability': 'Adaptability'},
    'Alolan Ninetales': {'base_stats': {'hp': 73, 'attack': 67, 'defense': 75, 'special_attack': 81, 'special_defense': 100, 'speed': 109}, 'types': ['Ice', 'Fairy']},
    'Lapras': {'base_stats': {'hp': 130, 'attack': 85, 'defense': 80, 'special_attack': 85, 'special_defense': 95, 'speed': 60}, 'types': ['Water', 'Ice']},
    'Hisuian Sneasler': {'base_stats': {'hp': 80, 'attack': 130, 'defense': 60, 'special_attack': 40, 'special_defense': 80, 'speed': 120}, 'types': ['Fighting', 'Poison']},
}
