"""Species database for the Pokémon Battle Engine.

Development Rule:
- Add complete evolution families.
- Include regional forms that belong to those families.
- Only store species names until mechanics require additional data.
"""

SPECIES = {
    'Gastly': {},
    'Haunter': {},
    'Gengar': {},
    'Litten': {},
    'Torracat': {},
    'Incineroar': {},
    'Sneasel': {},
    'Weavile': {},
    'Sneasel (Hisui)': {},
    'Sneasler': {},
    'Cresselia': {},
    'Wattrel': {},
    'Kilowattrel': {},
    'Poltchageist': {},
    'Sinistcha': {},
    'Calyrex-Ice': {},
    'Indeedee-F': {},
    'Lunala': {},
    'Ursaluna': {},
    'Torkoal': {},
    'Houndoom': {},
    'Talonflame': {},
    'Iron Hands': {},
    'Alakazam': {},
    'Clefable': {},
    'Scizor': {},
    'Tyranitar': {},
    'Excadrill': {},
    'Milotic': {},
    'Volcarona': {},
    'Aegislash': {},
    'Amoonguss': {},
    'Gholdengo': {},
    'Dragonite': {},
    'Archaludon': {},
    'Rotom-Wash': {},
    'Groudon': {},
    'Charizard': {},
    'Venusaur': {},
    'Flutter Mane': {},
    'Pelipper': {},
    'Barraskewda': {},
    'Swampert': {},
    'Politoed': {},
    'Kingdra': {},
    'Abomasnow': {},
    'Lucario': {},
    'Alolan Ninetales': {},
    'Lapras': {},
    'Sneasler (Hisui)': {},
}
